openapi: 3.0.3
info:
    title: TCSS 460 Group Project API
    description: |
        **Team:** Team 9
        **Deployed URL:** https://tcss460-team-9-api-72a4ffcce368.herokuapp.com

        A RESTful API for the TCSS 460 group project.
    version: 0.1.0

servers:
    - url: http://localhost:3000
      description: Local development
    - url: https://tcss460-team-9-api-72a4ffcce368.herokuapp.com
      description: Production environment

tags:
    - name: General
      description: General-purpose routes

paths:
    /status:
        get:
            tags: [General]
            summary: Status
            description: Get the status of the server.
            responses:
                '200':
                    description: Server is alive.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        example: 'Alive'
    /movies:
        get:
            tags: [General]
            summary: Search for movies with query strings
            description: Returns movies matching search query. With no parameters, returns movies sorted by popularity in descending order.
            parameters:
                - name: page
                  in: query
                  required: false
                  schema:
                      type: integer
                      default: 0
                      minimum: 0
                  description: Page number from the results
                - name: text
                  in: query
                  required: false
                  schema:
                      type: string
                      example: Knight,crime
                  description: Search for (case-insensitive) keywords in the title or description. Comma-seperated single words
                - name: after
                  in: query
                  required: false
                  schema:
                      type: string
                      example: 2022-05-17
                  description: Earliest release date allowed among search results (exclusive)
                - name: before
                  in: query
                  required: false
                  schema:
                      type: string
                      example: 2026-03-22
                  description: Latest release date allowed among search results (exclusive)
                - name: sort
                  in: query
                  required: false
                  schema:
                      type: string
                      default: popularity
                      enum: [title, popularity, date, rating]
                  description: Field to sort on
                - name: order
                  in: query
                  required: false
                  schema:
                      type: string
                      default: desc
                      enum: [asc, desc]
                  description: Sorting order
            responses:
                '200':
                    description: One page of returned movies, for a maximum of 20 movies per page.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/MoviesSearchResponse'
                '400':
                    description: Bad query string
                '500':
                    description: Internal server error
                '502':
                    description: Failed to reach external API

                                
# ── Schemas ───────────────────────────────────────────────────

components:
    schemas:
        MoviesSearchResponse:
            type: object
            properties:
                code:
                    type: integer
                    example: 200
                page:
                    type: integer
                    example: 0
                total_pages:
                    type: integer
                    example: 1
                total_results:
                    type: integer
                    example: 1
                results:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: integer
                                example: 961323
                            lang:
                                type: string
                                example: en
                            title:
                                type: string
                                example: Nimona
                            description:
                                type: string
                                example: A knight framed for a tragic crime teams with a scrappy, shape-shifting teen to prove his innocence.
                            release_date:
                                type: string
                                example: 2023-06-23
                            poster:
                                type: string
                                example: TBD # TODO: Do we host these local? Do we pass a blob of image data from TMDB? Do we pass along an absolute url to TMDB?

        MovieResponse:
            type: object
            properties:
                code:
                    type: integer
                    example: 200
                id:
                    type: integer
                    example: 961323
                lang:
                    type: string
                    example: en
                title:
                    type: string
                    example: Nimona
                description:
                    type: string
                    example: A knight framed for a tragic crime teams with a scrappy, shape-shifting teen to prove his innocence.
                release_date:
                    type: string
                    example: 2023-06-23
                poster:
                    type: string
                    example: TBD # TODO: Do we host these local? Do we pass a blob of image data from TMDB? Do we pass along an absolute url to TMDB?
                duration:
                    type: integer
                    example: 99