name: CI

on:
  - pull_request
  - push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Format Check
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npx prisma generate && npm run build

      - name: Test
        run: npx prisma generate && npm test
